# Generated by Django 2.2.3 on 2019-07-19 20:15

import ckeditor_uploader.fields
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('title', models.CharField(max_length=512)),
                ('author', models.TextField(max_length=128)),
                ('uploader', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ts_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('word_art', models.ImageField(null=True, upload_to='')),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('author', models.IntegerField(default=1)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('document', models.ManyToManyField(related_name='document_set', to='documents.DocumentModel')),
            ],
        ),
        migrations.CreateModel(
            name='CitationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_by', models.ManyToManyField(related_name='cited_me', to='documents.DocumentModel')),
                ('cited_to', models.ManyToManyField(related_name='i_cited', to='documents.DocumentModel')),
            ],
        ),
    ]
