# Generated by Django 2.2.3 on 2019-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='uploader',
            field=models.IntegerField(default=1),
        ),
    ]
