# Generated by Django 2.2.3 on 2019-07-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmodel',
            old_name='text',
            new_name='ocr_text',
        ),
    ]
