# Generated by Django 2.2.3 on 2019-07-19 16:46

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20190719_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='ts_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
