# Generated by Django 2.2.3 on 2019-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentmodel_ts_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='word_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
