# Generated by Django 2.2.3 on 2019-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_forumpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordmodel',
            name='document',
            field=models.ManyToManyField(related_name='documents', to='documents.DocumentModel'),
        ),
    ]
