# Generated by Django 2.2.3 on 2019-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20190720_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordmodel',
            name='document',
            field=models.ManyToManyField(related_name='document_set', to='documents.DocumentModel'),
        ),
    ]
